version: '3'

services:
    cardindexclean:
        build: .
        image: cardindexclean
        entrypoint: .docker/entrypoint.sh
        ports: 
            - 3000:3000
        volumes: 
            - ./:/home/node
